import { Inter } from 'next/font/google'
import './globals.css'
//import Loader from './components/Loader'
import NextTopLoader from 'nextjs-toploader';
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <NextTopLoader
  color="red"
  initialPosition={0.8}
  crawlSpeed={100}
  height={3}
  crawl={true}
  showSpinner={false}
  easing="ease"
  speed={2000}
  shadow="0 0 10px #2299DD,0 0 5px #2299DD"
  template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
  zIndex={1600}
  showAtBottom={false}
/>
        {children}
      
      </body>
      
    </html>
  )
}
